# Project language
language: php
php:
    - 7.2

# Allows use container-based infrastructure
sudo: false

# Start mysql service
services:
    - postgresql
    - redis-server
    - rabbitmq

# Cache composer packages so "composer install" is faster
cache:
    directories:
        - $HOME/.composer/cache/files

# Update composer
before-install:
    - composer self-update

install:
    - cp backend/.env.dist backend/.env
    - composer install -o -d backend
env:
    global:
        - DATABASE_URL=pgsql://cpiapps:cpiapps@127.0.0.1:5432/cpiapps
        - REDIS_URL=redis://127.0.0.1
        - RABBITMQ_URL=amqp://guest:guest@127.0.0.1:5672

before_script:
    - psql -c "CREATE DATABASE cpiapps;" -U postgres
    - psql -c "CREATE USER cpiapps WITH PASSWORD 'cpiapps';" -U postgres

script:
    - ./backend/bin/console lint:yaml ./backend/config
    - composer validate --strict -d backend
    - ./backend/bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction
    - ./backend/bin/console doctrine:schema:update --force
    - ./backend/bin/console hautelook:fixtures:load -n --purge-with-truncate
    - ./backend/vendor/bin/behat --config ./backend/behat.yml -n