# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7.2-fpm

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - apt-get update && apt-get install -y unzip libssl-dev libicu-dev zip git zlib1g-dev libpq-dev librabbitmq-dev
          - docker-php-ext-install -j$(nproc) zip json intl pdo pdo_pgsql pgsql opcache bcmath
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - export APP_ENV=dev DATABASE_URL=pgsql://cpiapps:cpiapps@localhost:5432/cpiapps
          - composer install -o -d backend
          - ./backend/vendor/bin/behat --config ./backend/behat.yml
        services:
          - postgres
definitions:
  services:
    postgres:
      image: postgres:11-alpine
      environment:
        POSTGRES_DB: 'cpiapps'
        POSTGRES_USER: 'cpiapps'
        POSTGRES_PASSWORD: 'cpiapps'